# Generated by Django 3.2.20 on 2024-03-12 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='package',
            name='pic2',
        ),
        migrations.RemoveField(
            model_name='package',
            name='pic3',
        ),
        migrations.RemoveField(
            model_name='package',
            name='pic4',
        ),
        migrations.RemoveField(
            model_name='package',
            name='pic5',
        ),
    ]
