# Generated by Django 3.2.20 on 2024-03-14 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0002_auto_20240312_1440'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='pic2',
            field=models.ImageField(default='', upload_to='uploads'),
        ),
        migrations.AddField(
            model_name='package',
            name='pic3',
            field=models.ImageField(default='', upload_to='uploads'),
        ),
        migrations.AddField(
            model_name='package',
            name='pic4',
            field=models.ImageField(default='', upload_to='uploads'),
        ),
        migrations.AddField(
            model_name='package',
            name='pic5',
            field=models.ImageField(default='', upload_to='uploads'),
        ),
    ]
