# Generated by Django 3.2.20 on 2024-03-16 04:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0004_buyer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Checkout',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('qty', models.IntegerField(default=1)),
                ('total', models.IntegerField()),
                ('gst', models.IntegerField(default=0)),
                ('final', models.IntegerField()),
                ('rppid', models.CharField(blank=True, default='', max_length=30, null=True)),
                ('date', models.DateTimeField(auto_now=True)),
                ('payment', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('billing_Name', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('billing_Phone', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('billing_Address', models.TextField(blank=True, default='', null=True)),
                ('billing_PIN', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('billing_City', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('billing_State', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('shipping_Name', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('shipping_Phone', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('shipping_Address', models.TextField(blank=True, default='', null=True)),
                ('shipping_PIN', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('shipping_City', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('shipping_State', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('package', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='mainApp.package')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainApp.buyer')),
            ],
        ),
    ]
